---
title: "Report for Project One: Nearest Neighbors"
author: "Kaitlyn Grubb"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Report for Project One: Nearest Neighbors}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r data}
data.name.vec <- c(
  "spam",
  "SAheart",
  "zip.train",
  "prostate",
  "ozone")
data.list <- list()
library(ElemStatLearn)
for(data.name in data.name.vec)
{
  data(list = data.name, package="ElemStatLearn")
  data.list[[data.name]] <- get(data.name)
}
str(data.list)

is.binary <- ElemStatLearn::zip.train[,1] %in% c(0,1)

data.list <- list(
  spam=list(
    label.vec=ifelse(ElemStatLearn::spam$spam=="spam", 1, 0),
    feature.mat=as.matrix(ElemStatLearn::spam[, -ncol(ElemStatLearn::spam)])),
  zip.train=list(
    label.vec=ElemStatLearn::zip.train[is.binary,1],
    feature.mat=ElemStatLearn::zip.train[is.binary,-1])
)

for(data.name in names(data.list))
{
  one.data.set <- data.list[[data.name]]
  set.seed(1)
  fold.vec <- sample(rep(1:n.folds, l=nrow(one.data.set$feature.mat)))
  NearestNeighborsCV(one.data.set$feature.mat, one.data.set$label.vec)
}
```